'use client';

import Head from 'next/head'
import {gsap,Power4} from 'gsap';
import { useEffect } from 'react';


export default function Home() {

  useEffect(()=>{
      const hero=document.querySelector('.hero');
      const slider=document.querySelector('.slider');
      const menu=document.querySelector('.menu');
    gsap.to(hero,{height:'80%',duration:1,ease:Power4.out});
    gsap.to(hero,{width:'80%',duration:1,ease:Power4.out,delay:1.2 });
    gsap.fromTo(slider,{height:'0%'},{height:'100%',duration:1,ease:Power4.out,delay:1.2});
    gsap.fromTo('#logo',{opacity:0},{opacity:1,duration:1,delay:1.2})
    gsap.fromTo('.menu',{opacity:0},{opacity:1,duration:1,delay:1.2})
    gsap.fromTo('.headline',{opacity:0,x:0},{opacity:1,x:30,duration:1,delay:1.5})
    },[]);
    
  return (
    <div>
      <Head>
        <title>Animation website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </Head>
      <header>
        <nav>
          <h3 id="logo">Audi</h3>
          <span className="material-symbols-outlined menu">
            menu
          </span>
        </nav>

        <section>
          <div className="hero">
            <img src="/img/car.jpg" alt=""  />
            <h1 className="headline">TT coupe</h1>
          </div>
        </section>
      </header>
      <div className="slider"></div>
    </div>
  )
}
