'use client';

import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import {gsap,Power3,Power4} from 'gsap';
import { useEffect } from 'react';
import { width } from '@mui/system';


export default function Home() {
  useEffect(()=>{
      const hero=document.querySelector('.hero');
      const slider=document.querySelector('.slider');
      const menu=document.querySelector('.menu');
    //   console.log(hero);
    //   const tl=gsap.timeline();
    //   tl.fromTo(hero,1,{height:'0%'},{height:'80%',ease:Power2.easeInOut});
    gsap.to(hero,{height:'80%',duration:1,ease:Power4.out});
    gsap.to(hero,{width:'80%',duration:1,ease:Power4.out,delay:1.2 });
    gsap.fromTo(slider,{height:'0%'},{height:'100%',duration:1,ease:Power4.out,delay:1.2});
    gsap.fromTo('#logo',{opacity:0},{opacity:1,duration:1,delay:1.2})
    gsap.fromTo('.menu',{opacity:0},{opacity:1,duration:1,delay:1.2})
    gsap.fromTo('.headline',{opacity:0,x:0},{opacity:1,x:30,duration:1,delay:1.5})
    },[]);
  
  // const headline=document.querySelector('.headline');
  // const heroRef=useRef();
    // const textRef=useRef<HTMLDivElement | null>(null);

  return (
    <div>
      <Head>
        <title>Animation website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </Head>
      <header>
        <nav>
          <h3 id="logo">Audi</h3>
          <span className="material-symbols-outlined menu">
            menu
          </span>
          {/* <img src="menu.png" alt="" srcset="" /> */}
        </nav>

        <section>
          <div className="hero">
            <img src="/img/car.jpg" alt=""  />
            <h1 className="headline">TT coupe</h1>
          </div>
        </section>
      </header>
      <div className="slider"></div>
      {/* <hr /> */}
      {/* <div className="test">
      <p>test-1</p>
      <p>test-2</p>
      <p>test-3</p>
      <p>test-4</p>
      <p>test-5</p>
    </div> */}
    <script src='https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.5/gsap.min.js'></script>

    </div>
  )
}
